# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pull Metadata
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: cameta
      with:
        proj-path: CivicAddress/CivicAddress.csproj
    - name: Package
      run: dotnet pack --no-restore -c Release -o out -v d
    - name: Deploy
      run: dotnet nuget push "out/CivicAddress.${{steps.cameta.outputs.package-version}}.nupkg" --source "github" -n
